plugins {
    id 'com.android.library'
    }

group = 'com.deepanshuchaudhary.pdf_manipulator'
version = '1.0-SNAPSHOT'

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://repo.itextsupport.com/android"
        }
    }
}

android {
    namespace = 'com.deepanshuchaudhary.pdf_manipulator'

    compileSdk = 37

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk = 21
    }

    dependencies {
        implementation 'androidx.core:core-ktx:1.9.0'

        implementation 'org.slf4j:slf4j-api:1.7.36'

        implementation 'com.itextpdf.android:kernel-android:7.2.4'
        implementation 'com.itextpdf.android:layout-android:7.2.4'
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    }
}
